using System.Windows.Input;

namespace SoulExe.ViewModels;

public sealed partial class MainViewModel
{
    public AsyncRelayCommand SendCommand { get; }
    public AsyncRelayCommand StartModelCommand { get; }
    public AsyncRelayCommand StopModelCommand { get; }
    public AsyncRelayCommand ToggleModelStartStopCommand { get; }
    public AsyncRelayCommand InstallEngineCommand { get; }
    public AsyncRelayCommand UseStarterModelCommand { get; }
    public AsyncRelayCommand ToggleNetworkCommand { get; }
    public RelayCommand CopyNetworkAddressCommand { get; }
    public AsyncRelayCommand AddCharacterCommand { get; }
    public RelayCommand ToggleCharacterGeneratorCommand { get; }
    public RelayCommand OpenCharacterCreationDialogCommand { get; }
    public RelayCommand SelectCharacterCreationModeCommand { get; }
    public RelayCommand CloseCharacterCreationDialogCommand { get; }
    public AsyncRelayCommand CreateCharacterWithNameCommand { get; }
    public AsyncRelayCommand GenerateCharacterFromIdeaCommand { get; }
    public AsyncRelayCommand ImportCharacterCommand { get; }
    public AsyncRelayCommand ImportSoulOfWaifuCommand { get; }
    public AsyncRelayCommand ExportCharacterCommand { get; }
    public AsyncRelayCommand DeleteCharacterCommand { get; }
    public AsyncRelayCommand OpenCharacterChatCommand { get; }
    public AsyncRelayCommand OpenCharacterEditorCommand { get; }
    public AsyncRelayCommand ConfirmDeleteCharacterCommand { get; }
    public AsyncRelayCommand ConfirmCharacterDeleteCommand { get; }
    public RelayCommand CancelCharacterDeleteCommand { get; }
    public AsyncRelayCommand AddChatCommand { get; }
    public AsyncRelayCommand ConfirmNewChatForCharacterCommand { get; }
    public RelayCommand CancelNewChatCharacterPickerCommand { get; }
    public AsyncRelayCommand ToggleChatPinnedCommand { get; }
    public AsyncRelayCommand ToggleConversationPinnedCommand { get; }
    public RelayCommand BeginRenameConversationCommand { get; }
    public AsyncRelayCommand DeleteConversationCommand { get; }
    public AsyncRelayCommand ConfirmPendingDeletionCommand { get; }
    public RelayCommand CancelPendingDeletionCommand { get; }
    public AsyncRelayCommand ConfirmRenameSceneCommand { get; }
    public RelayCommand CancelRenameSceneCommand { get; }
    public RelayCommand OpenChatActionMenuCommand { get; }
    public RelayCommand CloseChatActionMenuCommand { get; }
    public AsyncRelayCommand ConfirmRenameChatCommand { get; }
    public RelayCommand CancelRenameChatDialogCommand { get; }
    public RelayCommand OpenMessageActionMenuCommand { get; }
    public RelayCommand CloseMessageActionMenuCommand { get; }
    public RelayCommand ToggleChatMessageSearchCommand { get; }
    public RelayCommand CloseChatMessageSearchCommand { get; }
    public RelayCommand SelectChatMessageSearchResultCommand { get; }
    public RelayCommand ToggleSceneMessageSearchCommand { get; }
    public RelayCommand CloseSceneMessageSearchCommand { get; }
    public RelayCommand SelectSceneMessageSearchResultCommand { get; }
    public RelayCommand LoadOlderChatMessagesCommand { get; }
    public RelayCommand LoadOlderSceneMessagesCommand { get; }
    public RelayCommand ToggleCharacterCardSectionCommand { get; }
    public AsyncRelayCommand DeleteChatCommand { get; }
    public AsyncRelayCommand CreateChatForCharacterCommand { get; }
    public AsyncRelayCommand DeleteChatListItemCommand { get; }
    public RelayCommand BeginRenameChatCommand { get; }
    public AsyncRelayCommand SaveRenameChatCommand { get; }
    public RelayCommand CancelRenameChatCommand { get; }
    public AsyncRelayCommand SaveCharacterCommand { get; }
    public AsyncRelayCommand ExpandCharacterFieldCommand { get; }
    public AsyncRelayCommand PreviousVariantCommand { get; }
    public AsyncRelayCommand NextVariantCommand { get; }
    public RelayCommand BeginEditMessageCommand { get; }
    public RelayCommand CancelEditMessageCommand { get; }
    public AsyncRelayCommand SaveEditMessageCommand { get; }
    public AsyncRelayCommand DeleteMessageCommand { get; }
    public AsyncRelayCommand ContinueFromMessageCommand { get; }
    public AsyncRelayCommand SearchModelsCommand { get; }
    public AsyncRelayCommand DownloadSelectedModelCommand { get; }
    public AsyncRelayCommand LoadRecommendedModelsCommand { get; }
    public AsyncRelayCommand DownloadRecommendedModelCommand { get; }
    public RelayCommand PauseModelDownloadCommand { get; }
    public AsyncRelayCommand ResumeModelDownloadCommand { get; }
    public RelayCommand ToggleModelDownloadCommand { get; }
    public RelayCommand CancelModelDownloadCommand { get; }
    public AsyncRelayCommand RefreshInstalledModelsCommand { get; }
    public AsyncRelayCommand UseInstalledModelCommand { get; }
    public AsyncRelayCommand SaveModelSettingsCommand { get; }
    public AsyncRelayCommand SaveChatAppearanceCommand { get; }
    public AsyncRelayCommand SaveMobileAccessCommand { get; }
    public RelayCommand ResetChatAppearanceCommand { get; }
    public RelayCommand SelectOptionsTabCommand { get; }
    public RelayCommand SetChatAppearanceColorCommand { get; }
    public AsyncRelayCommand AddLorebookCommand { get; }
    public RelayCommand OpenLibraryLoreEditorCommand { get; }
    public RelayCommand CloseLibraryLoreEditorCommand { get; }
    public AsyncRelayCommand DeleteLoreEntryCommand { get; }
    public AsyncRelayCommand DeleteLorebookCommand { get; }
    public AsyncRelayCommand SaveLorebookCommand { get; }
    public AsyncRelayCommand AddLoreEntryCommand { get; }
    public AsyncRelayCommand AddPersonaCommand { get; }
    public RelayCommand OpenPersonaEditorCommand { get; }
    public RelayCommand ClosePersonaEditorCommand { get; }
    public AsyncRelayCommand SavePersonaCommand { get; }
    public RelayCommand ConfirmDeletePersonaCommand { get; }
    public AsyncRelayCommand DeletePersonaCommand { get; }
    public RelayCommand CancelPersonaDeleteCommand { get; }
    public RelayCommand ChoosePersonaAvatarCommand { get; }
    public AsyncRelayCommand LoadGatewayTrendingCommand { get; }
    public AsyncRelayCommand SearchGatewayCommand { get; }
    public RelayCommand SetGatewayCategoryCommand { get; }
    public AsyncRelayCommand ImportGatewayAssetCommand { get; }
    public AsyncRelayCommand LoadMoreGatewayCommand { get; }
    public AsyncRelayCommand UpdateMemoryCommand { get; }
    public AsyncRelayCommand UpdateSummaryCommand { get; }
    public AsyncRelayCommand SetupInstallEngineCommand { get; }
    public AsyncRelayCommand SetupSelectAndInstallBackendCommand { get; }
    public AsyncRelayCommand SetupDownloadRecommendedCommand { get; }
    public AsyncRelayCommand SkipInitialSetupCommand { get; }
    public AsyncRelayCommand NextInitialSetupStepCommand { get; }
    public RelayCommand PreviousInitialSetupStepCommand { get; }
    public AsyncRelayCommand SetupStartChatCommand { get; }
    public AsyncRelayCommand CreateSceneCommand { get; }
    public RelayCommand BeginCreateSceneCommand { get; }
    public RelayCommand CancelCreateSceneCommand { get; }
    public AsyncRelayCommand SaveSceneCommand { get; }
    public AsyncRelayCommand DeleteSceneCommand { get; }
    public AsyncRelayCommand StartSceneCommand { get; }
    public AsyncRelayCommand PauseSceneCommand { get; }
    public AsyncRelayCommand ToggleSceneStartPauseCommand { get; }
    public AsyncRelayCommand NextSceneTurnCommand { get; }
    public AsyncRelayCommand ChooseSceneSpeakerCommand { get; }
    public AsyncRelayCommand SendGroupMessageCommand { get; }
    public AsyncRelayCommand FinishSceneCommand { get; }
    public RelayCommand SelectCharacterEditorTabCommand { get; }
    public AsyncRelayCommand ContinueChatCommand { get; }
    public AsyncRelayCommand SaveChatStartingContextCommand { get; }
    public RelayCommand NavigateCommand { get; }
    public RelayCommand SelectLibraryTabCommand { get; }
    public RelayCommand SetModelsHubTabCommand { get; }
    public RelayCommand ChooseServerCommand { get; }
    public AsyncRelayCommand ChooseModelCommand { get; }
    public RelayCommand ChooseAvatarCommand { get; }
}
