$ts = [DateTime]::Now.ToString("dd.MM.yyyy HH:mm")
$content = @"
// <auto-generated/>
namespace SoulExe;
internal static class BuildInfo
{
    public const string BuildNumber = "412";
    public const string BuildTime = "$ts";
}
"@
[System.IO.File]::WriteAllText($args[0], $content)
