<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>SoulExe</AssemblyName>
    <ApplicationIcon>Assets\SoulExe.ico</ApplicationIcon>
    <RootNamespace>SoulTextWpf</RootNamespace>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\SoulExe.ico" />
    <Resource Include="Assets\SoulExeWindowIcon.png" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <EmbeddedResource Include="Assets\recommended_models.json" />
  </ItemGroup>
</Project>
